# Generated by Django 4.0.6 on 2022-11-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_guest_options_guest_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='gender',
            field=models.CharField(choices=[('1', 'Laki-laki'), ('2', 'Perempuan')], default='1', max_length=1),
        ),
    ]
