# Generated by Django 4.0.6 on 2022-12-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_guest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['reserve_time', '-created']},
        ),
    ]
